Bootstrap feature
Byabasaija/News_Week_Clone pull request #2
Opened 2020-11-05 15:36 UTC by krishnzzz

In the creation of a replica of the Newsweek, the following tasks were done:

- Create index.html
- Create style.css and link to HTML
- Gather all required texts, icons, images and fonts from the page.
- Create a proper folder structure to retrieve assets easily.
- Include all required contents of the page in the index.html file using proper HTML5 Semantics.
- Create required font-faces for the texts of the page.
- Add all required styling like color, font-size, font-family, font-weight, text-decoration, width & height and margin & padding to make the page look as similar to the original as possible.
- Place all items at the required positions for Mobile.
- Use Bootstrap for positioning and sizing.
- Use Bootstrap to add responsiveness for Tablet and Desktop versions.
- Make sure all items are well placed on the pages for each screen sizes.
- Check for and fix according to linter requirements.

All of the works have been done in proper collaboration by both partners working on the project.

Thank You.

2020-11-05 15:37 UTC, krishnzzz commented
NOTE: Branch "main2" has been used due to wrongly creating "main" branch.

2020-11-05 18:17 UTC, uryelah requested changes
Hi **Pascal Byabasaija & Suyash Fowdar**, I'm Sarah your reviewer for this PR 👩‍🚀 

You guys did a great job building this project!
One of the things a lot of people have difficulties with and you had no issues with is keeping the proportion of the images and making sure to use SVG logos, so congrats for that!

Now, this project requires a bit more of you, style wise, than the previous ones since it's built with the help of Bootstrap.

That means this clone needs to be even closer than the last ones and that you should be using as many Bootstrap classes as possible, to get used to it and understand how powerful the tool is.

So before anything make sure to open the [original NewsWeek](https://www.newsweek.com/) page and carefully compare it with your clone side by side, notice if the spacings, borders, positions are the same, and what can be improved to make your clone similar.

Then read the comments below carefully and try to implement them to the best of your habilities!

You are really close to the finish line so keep on coding and Rock on! 🎸 👨‍🎤 

# Required Changes 🏗️ 🐛 💡

-----

 **Kindly fix the pointed out items and comments below before requesting the next code review**


- [x] Let's try to use the positioning, overflow, or the scroll property of the three top columns of the page so that the empty white space is removed from under them in the large and medium screen sizes:
![Screenshot_2020-11-05 Newsweek - News, Analysis, Politics, Business, Technology](https://user-images.githubusercontent.com/16193212/98277067-aa13ef80-1f75-11eb-906d-77ea9044b1f4.png)

- [x] The first article of the 'In the Magazine' section takes more vertical space than the other artices. Make sure to style it accordingly:

**Compare the original site on larger screens and your clone in the screenshots below:**

 <table style="width:100%">
  <tr>
    <th>Original Page</th>
    <th>Clone</th>
  </tr>
  <tr>
    <td valign="top"><img src=https://user-images.githubusercontent.com/16193212/98277345-06770f00-1f76-11eb-9cc6-2aa88832d4d6.png /></td>
    <td><img src=https://user-images.githubusercontent.com/16193212/98277349-07a83c00-1f76-11eb-9670-86333cd846f6.png /></td>
  </tr>
</table> 

---

- [x] Most of the sections and titles of the NewsWeek page have an horizontal light grey separator. Make sure to add the missing separators to the clone:
![Screenshot_2020-11-05 Newsweek(3)](https://user-images.githubusercontent.com/16193212/98277952-b3518c00-1f76-11eb-83b4-08135ffe25bd.png)
![Screenshot_2020-11-05 Newsweek(2)](https://user-images.githubusercontent.com/16193212/98277958-b3ea2280-1f76-11eb-8ef0-a521c263cc9f.png)
![Screenshot_2020-11-05 Newsweek(1)](https://user-images.githubusercontent.com/16193212/98277961-b482b900-1f76-11eb-8b0c-44a2341aa105.png)
![Screenshot_2020-11-05 Newsweek(5)](https://user-images.githubusercontent.com/16193212/98277962-b482b900-1f76-11eb-8825-997409452b74.png)
![Screenshot_2020-11-05 Newsweek(4)](https://user-images.githubusercontent.com/16193212/98277966-b51b4f80-1f76-11eb-89c3-352193ff1f4e.png)

---

- [x] The Footer links have each a light grey vertical bar at their right, a `|`, between each link.
You can make those by combining paddings and border-right or using the [::after pseudo element. ](https://developer.mozilla.org/en-US/docs/Web/CSS/::after)

**Compare the original site and your clone in the screenshots below:**

 <table style="width:100%">
  <tr>
    <th>Original Page</th>
    <th>Clone</th>
  </tr>
  <tr>
    <td valign="top"><img src=https://user-images.githubusercontent.com/16193212/98278383-468ac180-1f77-11eb-9ff2-601f1da222a7.png /></td>
    <td><img src=https://user-images.githubusercontent.com/16193212/98278381-45599480-1f77-11eb-846b-cd83ab1e7602.png /></td>
  </tr>
</table> 

---

- [ ] In large screens the NewsWeek website content takes a maximum width of 1310px and has grey margins/background around its sides.
Try to implement the max-content and grey background in your clone:

**Compare the original site and your clone in the screenshots below:**

 <table style="width:100%">
  <tr>
    <th>Original Page</th>
    <th>Clone</th>
  </tr>
  <tr>
    <td valign="top"><img src=https://user-images.githubusercontent.com/16193212/98278868-f3fdd500-1f77-11eb-9d68-0dfec089d97a.png /></td>
    <td><img src=https://user-images.githubusercontent.com/16193212/98278866-f2cca800-1f77-11eb-983b-dfd2fca65460.png /></td>
  </tr>
</table> 

---

- [ ] Let's center the article images and text in small screens, < 767px , like in the original page.

**Compare the original site and your clone in the screenshots below:**

 <table style="width:100%">
  <tr>
    <th>Original Page</th>
    <th>Clone</th>
  </tr>
  <tr>
    <td valign="top"><img src=https://user-images.githubusercontent.com/16193212/98279290-771f2b00-1f78-11eb-901a-5f0ef2c9b4bf.png /></td>
    <td><img src=https://user-images.githubusercontent.com/16193212/98279297-78e8ee80-1f78-11eb-924f-fdf5d84c608c.png /></td>
  </tr>
</table> 

---

- [ ] Make sure the 'Subscribe' image has two superposed magazine covers like the original page in all screensizes.

- [ ] Make sure the 'NewsLetter' section image is aligned properly, taking 100% of the width and keeping it's proportions, on small screens.

**Compare the original site and your clone in the screenshots below:**

 <table style="width:100%">
  <tr>
    <th>Original Page</th>
    <th>Clone</th>
  </tr>
  <tr>
    <td valign="top"><img src=https://user-images.githubusercontent.com/16193212/98279772-265c0200-1f79-11eb-9455-425b4b6e796f.png /></td>
    <td><img src=https://user-images.githubusercontent.com/16193212/98279768-24923e80-1f79-11eb-9324-569017c05162.png /></td>
  </tr>
</table> 

------------

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

2020-11-05 18:17 UTC, uryelah commented on styles/style.css
> +}
- [ ] The focus of this project is to use as much Bootstrap classes as possible, whenever possible.
Though your code works well you can use Bootstrap classes to set margins and paddings of 0, so let's try to apply those styles with them.
Check the [Bootstrap documentation here](https://getbootstrap.com/docs/4.0/utilities/spacing/) if you are not sure how to implement this request.

2020-11-05 18:17 UTC, uryelah commented on styles/style.css
> +  position: fixed;
- [ ]  The position property is another one that can be implemented with Bootstrap classes. Check [the documentation here](https://getbootstrap.com/docs/4.0/utilities/position/) and apply this style with Boostrap instead.

2020-11-05 18:17 UTC, uryelah commented on styles/style.css
> +  padding-top: 0;
- [ ] Let's apply those styles with Bootstrap too, you can [even specify the side of the padding with the Bootstrap](https://getbootstrap.com/docs/4.0/utilities/spacing/#examples) classes.

2020-11-05 18:17 UTC, uryelah commented on styles/style.css
> +  position: relative;
- [ ] This too can be done with Bootstrap.

2020-11-05 18:17 UTC, uryelah commented on styles/style.css
> +  display: block;
- [ ] Lets implement display properties with[ Bootstrap classes ](https://getbootstrap.com/docs/4.0/utilities/display/)instead.

2020-11-05 18:17 UTC, uryelah commented on styles/style.css
> +  border: 0;
- [ ] Let's use the [Bootstrap border 0 class](https://getbootstrap.com/docs/4.0/utilities/borders/) instead, for practice.

2020-11-05 18:17 UTC, uryelah commented on styles/style.css
> +  left: 0;
- [ ] Please refer to the comments above on applying these types of properties with Bootstrap for this project.

2020-11-05 18:17 UTC, uryelah commented on styles/style.css
> +  justify-content: flex-end;
- [ ] Did you know you can even set the justification and alignment of flex items with Bootstrap classes? 
Check [the documentation here](https://getbootstrap.com/docs/4.0/utilities/flex/) and apply it to your element.

2020-11-05 18:17 UTC, uryelah commented on styles/style.css
> +  font-weight: bold;
- [ ] You can set font weights with Bootstrap classes, check [the documentation here](https://getbootstrap.com/docs/4.0/utilities/text/#font-weight-and-italics), and try to implement it.

2020-11-05 18:17 UTC, uryelah commented on styles/style.css
> +}
- [ ] Check the comment above about flex and Bootstrap classes and try to implement those flex properties with [Bootstrap classes](https://getbootstrap.com/docs/4.0/utilities/flex/) instead of pure CSS.

2020-11-05 18:17 UTC, uryelah commented on styles/style.css
> +    display: none;
- [ ] Did you know you can change the display property of an element using responsive Bootstrap classes?
Check [the documentation here](https://getbootstrap.com/docs/4.0/utilities/display/#hiding-elements) and try to implement it in your project.

2020-11-05 18:17 UTC, uryelah commented on styles/style.css
> +    font-weight: bold;
- [ ] Let's implement this style with Bootstrap classes instead.

2020-11-05 18:17 UTC, uryelah commented on styles/style.css
> +    position: relative;
- [ ] Let's implement this style with Bootstrap classes instead.

2020-11-05 18:17 UTC, uryelah commented on styles/style.css
> +    margin: 0;
- [ ] Let's implement this style with Bootstrap classes instead. Check the comments above on margins and paddings with bootstrap and responsive Bootstrap classes.
Ex:
```
<p>This is a regularly spaced paraph.</p>
<p class="ml-5 ml-lg-0">And this one has left margin visible on xs, sm and md displays.</p>
```
[From this reference article.](https://mdbootstrap.com/docs/jquery/utilities/spacing/)

2020-11-05 18:17 UTC, uryelah commented on styles/style.css
> +    display: block;
- [ ] You can set the display property using responsive Bootstrap classes, if they fit you breakpoints.
[Check the documentation here.](https://getbootstrap.com/docs/4.0/utilities/display/#hiding-elements)

2020-11-05 18:17 UTC, uryelah commented on styles/style.css
> +  src: url("../assets/fonts/robotocondensed-bold-webfont.woff2");
- [ ] [OPTIONAL] Why don't you try using Google fonts CDNs or font links to implement typefonts instead of saving them in your assets? It could lighten a bit your asset folder.
[Check this article about the usage of google fonts.](https://flaviocopes.com/google-fonts/)

2020-11-05 18:17 UTC, uryelah commented on index.html
> +  <meta name="viewport" content="width=device-width, initial-scale=1.0">
- [ ] Add the `shrink-to-fit=no` property to your viewport meta tag like [recommended by Boostrap here](https://getbootstrap.com/docs/4.3/getting-started/introduction/#responsive-meta-tag).
`<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">`

A more detailed explanation about the function `shrink-to-fit` can be found in [this StackOverflow thread](https://stackoverflow.com/questions/33767533/what-does-the-shrink-to-fit-viewport-meta-attribute-do).

2020-11-05 18:17 UTC, uryelah commented on index.html
> +  <link rel="icon" type="image/ico" href="assets/icons/favicon.ico"/>
- Nice touch adding a favicon to the page!

2020-11-06 16:28 UTC, MuriloRoque approved these changes
## Status: Approved :green_circle: 

### Hello @krishnzzz and @Byabasaija :wave: 

### Thank you for making all of the requested changes. Your project is approved :clap: :clap: :clap: 

### You may merge, good luck with your next projects :rocket: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[![Twitter Follow](https://img.shields.io/twitter/follow/MuriloRoquePai1?label=Follow%20Murilo%20on%20Twitter&style=social)](https://twitter.com/MuriloRoquePai1)

2020-11-14 13:32 UTC, merged